# Generated by Django 2.2.9 on 2020-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateField(auto_created=True, verbose_name='注册时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('studentID', models.CharField(max_length=20, verbose_name='学号')),
                ('type', models.IntegerField(choices=[(0, '学生'), (1, '老师')], default=0, verbose_name='身份')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_created=True, verbose_name='借阅时间')),
                ('returnTime', models.DateTimeField(verbose_name='归还时间')),
                ('limitTime', models.IntegerField(default=30, verbose_name='借阅时长')),
                ('borrowBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Book', verbose_name='借阅书名')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='借阅人')),
            ],
            options={
                'verbose_name': '借阅表',
                'verbose_name_plural': '借阅表',
            },
        ),
    ]
