# Generated by Django 2.2.9 on 2020-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returnTime',
            field=models.DateTimeField(blank=True, verbose_name='归还时间'),
        ),
    ]
